import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import { InputCard, PasswordCard } from '../components'

export default function Home() {
  const [password, setPassword] = useState('')
  return (
    <>
      <Head>
        <title>Key Master</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-full h-screen bg-[#18171f]'>
        <div className='flex flex-col pt-16 px-4 max-w-xl mx-auto'>
          <h1 className='text-[#817d92] text-center text-base'>Key Master</h1>
          <PasswordCard password={password} />
          <InputCard setPassword={setPassword} />
        </div>
      </main>
    </>
  )
}
